- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: dockerEngineRG
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: dockerEngineRG
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: dockerEngineRG
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: dockerEngineRG
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: dockerEngineRG
      name: myNetworkSecurityGroup
      rules:
        - name: AllowAll
          protocol: Tcp
          destination_port_range: '*'
          access: Allow
          priority: 100
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: dockerEngineRG
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: dockerEngineRG
      name: dockerEngine
      vm_size: Standard_DS1_v2
      admin_username: vmadmin
      ssh_password_enabled: true
      admin_password: Password123!
      # ssh_public_keys:
      #   - path: /home/vmadmin/.ssh/authorized_keys
      #     key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCdbdybDeZseC7M+qT6Mz3vM8OFPrzXyOPf7UnXc3XuK0JkaKHFWKCpjTSPmDRHY8ZHmlTv3IJBG8aSmpkDk4uHNgEFV2YAHrD+6NT+URtZel74RhcKw2KADvIOgQvplcSb0WoGE8lZdinLPdHPZjmQZxMSiRyfY+VA3Pi47tSaJ/tEaxVoJdgo63ueSIg7CUa3zg4+DRrA7N+3b55J+xqJoCbG+c3WqiETxIurhY2uc4I148MTvEMEeU2CY2DCbgad46hrdX5XeM6YX5rREB4YmxXCBYP3eT9sASuSmVK6hM8Nmq1/5Cr8ONLYPhyimGZL3BxOg1uN7MjXW85aews0UL6cT0qbJgaZTkKYxpJdS8TIqWO6j4hFbTMUX9ROjNyEy8mP2VM6/23eC5vGyGql4XlMZQbZx6MZOrJ+BvSUPzmN6ZlIb0JA2tGt1O+bmGhst32iNHj5lGc4hf10INVEHU7ThlXxSkiFwQt+iTM5WaKEhdGaIotDVV+w64Xs+ErLMJSymtf6TsRC+HqsMqZKEUe3x/TeMQNhvKZKSr+CH//Y7/G2hUulPk9t4COO9BpEK8pjIdvjGo7i7tduRXSqMgc9UFeYIj4XQbC6DODI+SokhDsL5n74nwAEaoWWB+RPuB0DXdSfG5WFAETRUZB/nTISwlXflc3CApJDru2ow== vmadmin@vmNode1"
      network_interfaces: myNIC
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '18.04-LTS'
        version: latest